# Generated by Django 4.2.9 on 2024-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Nurse'), (3, 'Doctor'), (4, 'Patient')], default=4, null=True),
        ),
    ]
