# Generated by Django 4.2.9 on 2024-02-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_medicalrecord_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'NURSE'), (3, 'DOCTOR'), (4, 'PATIENT')], default=4, null=True),
        ),
    ]
