# Generated by Django 5.0.3 on 2024-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_status_alter_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='address',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(default='0123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
