# Generated by Django 5.0.3 on 2024-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_calendar_description_remove_calendar_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslots',
            field=models.ManyToManyField(to='core.timeslot'),
        ),
        migrations.DeleteModel(
            name='calendar',
        ),
    ]
