# Generated by Django 5.0.3 on 2024-03-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_appointment_timeslots_doctorschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientId',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslots',
            field=models.ManyToManyField(to='core.doctorschedule'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(null=True),
        ),
    ]
