# Generated by Django 5.0.3 on 2024-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_appointment_doctorid_appointment_patientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_files'),
        ),
    ]
