# Generated by Django 5.0.3 on 2024-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_survey_is_published_alter_option_option_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslots',
            field=models.ManyToManyField(blank=True, to='core.doctorschedule'),
        ),
    ]
