# Generated by Django 5.0.3 on 2024-04-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
